services:
  estadisticas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estadisticas
    restart: always
    environment:
      PORT: ${PORT}

      CONTENIDOS_SERVICE_BASE_URL: ${CONTENIDOS_SERVICE_BASE_URL}
      USUARIOS_SERVICE_BASE_URL: ${USUARIOS_SERVICE_BASE_URL}
      COMPRAS_SERVICE_BASE_URL: ${COMPRAS_SERVICE_BASE_URL}
      FRONTEND_SERVICE_BASE_URL: ${FRONTEND_SERVICE_BASE_URL}
      ESTADISTICAS_SERVICE_BASE_URL: ${ESTADISTICAS_SERVICE_BASE_URL}

      CONTENIDOS_SERVICE_PORT: ${CONTENIDOS_SERVICE_PORT}
      USUARIOS_SERVICE_PORT: ${USUARIOS_SERVICE_PORT}
      COMPRAS_SERVICE_PORT: ${COMPRAS_SERVICE_PORT}
      ESTADISTICAS_SERVICE_PORT: ${ESTADISTICAS_SERVICE_PORT}

      SUPABASE_PROJECT_URL: ${SUPABASE_PROJECT_URL}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}

      ADMIN_ESTADISTICAS_CORREO: ${ADMIN_ESTADISTICAS_CORREO}
      ADMIN_ESTADISTICAS_PASSWORD: ${ADMIN_ESTADISTICAS_PASSWORD}

      APP_BASE_URL: ${APP_BASE_URL}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

    depends_on:
      - estadisticas-redis

  estadisticas-redis:
    image: redis:latest
    container_name: estadisticas-redis
    restart: always
    volumes:
      - estadisticas-redis:/data

volumes:
  estadisticas-redis:

